version: '3'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      bash -c "python src/manage.py test api"
    environment:
      - POSTGRES_DATABASE_NAME=education
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=True

    depends_on:
        - db

  db:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_DB=education
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
