version: '3'

services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: jatal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "db:/var/lib/postgresql/data/"

volumes:
  db:

networks:
  web: