# Generated by Django 3.2 on 2021-05-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('journal_name', models.CharField(max_length=70, verbose_name='название журнала')),
                ('journal_description', models.TextField(verbose_name='краткое описание')),
                ('journal_href', models.URLField(verbose_name='ссылка на журнал')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('article', models.CharField(max_length=225, verbose_name='название статьи')),
                ('article_description', models.TextField(max_length=255, verbose_name='краткое описание')),
                ('author_name', models.CharField(max_length=80, verbose_name='автор статьи')),
                ('article_href', models.URLField(verbose_name='ссылка на статью')),
                ('journal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.journal', verbose_name='журнал')),
            ],
            options={
                'verbose_name': 'Статья журнала',
                'verbose_name_plural': 'Статьи журнала',
            },
        ),
    ]
