# Generated by Django 3.2 on 2021-05-09 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalcabinet', '0006_auto_20210404_1134'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('community_name', models.CharField(max_length=255, verbose_name='название сообщества')),
                ('community_description', models.TextField(max_length=255, verbose_name='краткое описание')),
                ('img', models.ImageField(upload_to='images/', verbose_name='фото сообщества')),
                ('community_topics', models.ManyToManyField(related_name='com_topic', to='personalcabinet.Topic')),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_support', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.community', verbose_name='сообщество')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='участник сообщества')),
            ],
            options={
                'verbose_name': 'Участник сообщеста',
                'verbose_name_plural': 'Участники сообщества',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('company_name', models.CharField(max_length=120, verbose_name='название компании')),
                ('company_logo', models.ImageField(upload_to='images/', verbose_name='фото компании')),
                ('company_description', models.TextField(max_length=255, verbose_name='краткое описание')),
                ('company_href', models.URLField(max_length=120, verbose_name='ссылка на компанию')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='админ компании')),
                ('company_members', models.ManyToManyField(related_name='company_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('company_article_link', models.URLField(max_length=255, verbose_name='ссылка на статью')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.company', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'Пост компании',
                'verbose_name_plural': 'Посты компании',
            },
        ),
        migrations.CreateModel(
            name='CommunityPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('comment_text', models.TextField(verbose_name='текст комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор комментария')),
                ('community_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalcabinet.post', verbose_name='пост сообщества')),
            ],
            options={
                'verbose_name': 'Комментарий поста сообщества',
                'verbose_name_plural': 'Комментарии поста сообщества',
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('community_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_pages.journalarticle', verbose_name='статья из журнала')),
                ('community_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.communitymember', verbose_name='автор')),
                ('community_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalcabinet.post', verbose_name='статья сообщества')),
                ('community_post_likes', models.ManyToManyField(related_name='com_post_likes', to=settings.AUTH_USER_MODEL)),
                ('community_post_views', models.ManyToManyField(related_name='com_post_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пост сообщества',
                'verbose_name_plural': 'Посты сообщества',
            },
        ),
    ]
