# Generated by Django 3.2 on 2021-05-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalcabinet', '0006_auto_20210404_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='agreement',
            field=models.BooleanField(null=True, verbose_name='соглашение'),
        ),
    ]
