# Generated by Django 3.2 on 2021-05-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalcabinet', '0007_post_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original',
            field=models.BooleanField(null=True, verbose_name='оригинал текста'),
        ),
    ]
