name: "deploy  project"

on:
  push:
    branches:
      - develop
    tags:
      - docker
      - jatal
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Push notify
        if: ${{ github.event_name == 'push' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} just pushed me ${{ github.ref }} into ${{ github.repository }} with comment "${{ github.event.head_commit.message }}"
            ${{ github.event.compare }}

      - name: PR notify
        if: ${{ github.event_name == 'pull_request' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} just opened PR in ${{ github.repository }} with comment "${{github.event.pull_request.title}}"
            ${{ github.event.pull_request.html_url }}
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v1

      - name: Bash Action
        uses: rethab/bash-action@v1

      - name: Docker build
        uses: docker/setup-buildx-action@v1

      - name: Run docker compose service db
        run: docker-compose -f docker-compose.yml -p jatal_test up --build --exit-code-from python

  build:
    runs-on: ubuntu-latest
    steps:
      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Build Docker Nginx Image
        run: docker image build . --file nginx/Dockerfile --tag qwer342/nginx:latest

      - name: Push Docker Nginx Image
        run: docker image push qwer342/nginx:latest

      - uses: actions/checkout@v2
      - name: Build Docker Python Image
        run: docker image build . --file Dockerfile --tag qwer342/python:latest

      - name: Push Docker Python Image
        run: docker image push qwer342/python:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Bash inatall and create env
        run: apk add --no-cache openssh-client bash
      - run: chmod +x setup_env.sh
      - run: bash setup_env.sh

      - name: SSh dir
        run: mkdir -p ~/.ssh

      - run: echo "${{ secrets.PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
      - run: cat ~/.ssh/id_rsa
      - run: chmod 700 ~/.ssh/id_rsa
      - run: eval "$(ssh-agent -s)"
      - run: ssh-add ~/.ssh/id_rsa
      - run: ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
      - run: chmod +x deploy.sh
      - run: scp  -o StrictHostKeyChecking=no -r .env docker-compose.prod.yml ec2-user@${{ secrets.EC2_PUBLIC_IP_ADDRESS }}:/home/ec2-user/app
      - run: bash deploy.sh