name: "deploy  project"

on:
  push:
    branches:
      - develop
    tags:
      - docker
      - jatal
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Push notify
        if: ${{ github.event_name == 'push' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} just pushed me ${{ github.ref }} into ${{ github.repository }} with comment "${{ github.event.head_commit.message }}"
            ${{ github.event.compare }}

      - name: PR notify
        if: ${{ github.event_name == 'pull_request' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} just opened PR in ${{ github.repository }} with comment "${{github.event.pull_request.title}}"
            ${{ github.event.pull_request.html_url }}
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
      - name: Run docker compose service db
        run: docker-compose -f docker-compose.yml up --build -d

      - name: Run api tests
        run: python src/manage.py test api

  build:
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Build Docker Python Image
        run: docker image build . --file Dockerfile --tag qwer342/jatal:latest

      - name: Push Docker Python Image
        run: docker image push qwer342/jatal:latest
