name: "deploy  project"
on:
  push:
    branches:
      - develop
    tags:
      - docker
      - jatal
jobs:
  develop-build:
    runs-on: "ubuntu-latest"
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }}"
      - run: echo "Start action"
      - run: docker-compose -f docker-compose.yml -p jatal_backend build
