name: "deploy  project"
on:
  push:
    branches:
      - develop
    tags:
      - docker
      - jatal
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Build Docker Python Image
        run: docker image build . --file Dockerfile --tag jatal:latest

      - name: Push Docker Python Image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: jatal:latest
        run: docker image push jatal:latest
