name: "deploy  project"
on:
  push:
    branches:
      - develop
    tags:
      - docker
      - jatal
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Build Docker Python Image
        run: docker image build . --file Dockerfile --tag jatal:latest

      - name: Push Docker Python Image
        run: docker image push jatal:latest
