name: "deploy  project"
on:
  push:
    branches:
      - develop
    tags:
      - docker
      - jatal
jobs:
  develop-build:
    runs-on: "ubuntu-latest"
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }}"
      - run: echo "Start action"

      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2
      - name: Build Docker Python Image
      - run: docker-compose -f docker-compose.yml -p jatal_backend build
